### PR TITLE
Add Sale/Quote endpoint

### PR DESCRIPTION
**Pull request by theducvu**

### CODE REVIEW

**Comment by jarekwg** [comment]
Thanks! Add tests please. :)

**Comment by theducvu** [comment]
I've added the Quote endpoint tests in the same format as Invoice tests. Let me know if that is okay.

**Comment by jarekwg** [comment]
Excellent, thank you!

**Comment by jarekwg** [comment]
Out in [1.2.4](https://github.com/uptick/pymyob/releases/tag/1.2.4).

**Comment by theducvu** [comment]
Thank you very much.

**Pull request merged**
