### PR TITLE
Journal tran

### PR DESCRIPTION
**Pull request by wardy3**
Add journal transaction query

However, the MYOB doco says you can only GET this endpoint.

When I specify GET instead of CRUD, pymyob looks like it insists on a uid= option to be passed in. It looks like the endpoints.py file is trying to simplify the support for multiple endpoints but the MYOB API is a bit inconsistent with the UID option.

So, the change I've made creates put_ post_ etc queries when they don't exist. Not sure how to fix this

### CODE REVIEW

**Comment by jarekwg** [comment]
I think in this case you want to put it in on two lines, using `ALL` and `GET`, like in this example:
https://github.com/uptick/pymyob/blob/069431e17f86242dd2f57ed81955d935e3a735da/myob/endpoints.py#L74-L75

**Comment by wardy3** [comment]
> I think in this case you want to put it in on two lines, using `ALL` and `GET`, like in this example:
> 
> https://github.com/uptick/pymyob/blob/069431e17f86242dd2f57ed81955d935e3a735da/myob/endpoints.py#L74-L75

aaah i get it. i misunderstood "all".
how's this?

**Comment by jarekwg** [comment]
Lovely!

**Comment by jarekwg** [comment]
Out in [1.2.17](https://github.com/uptick/pymyob/releases/tag/1.2.17).

Thanks for contributing!

**Pull request merged**
