### PR TITLE
#82 ALL endpoint for GeneralLedger accountregister

### LINKED ISSUE #82: Add endpoint ALL accountregister
pull request inbound

### PR DESCRIPTION
**Pull request by timrichardson**
Closes #82

### CODE REVIEW

**Comment by jarekwg** [comment]
Thanks for the PR! I'll get to it in the next day or so! :)

**Comment by jarekwg** [comment]
Code looks good! Please fix address test failures and I'll merge & publish!

**Comment by timrichardson** [comment]
I do not understand the errors Test / test (3.7) or (3.8). The tests pass on my machine (python 3.11).

**Comment by timrichardson** [comment]
test failure needed a reordering of lines to be in alphabetical order, I will remember that.

**Comment by jarekwg** [comment]
Out in [1.2.21](https://github.com/uptick/pymyob/releases/tag/1.2.21).

Thanks for contributing!

**Pull request merged**
