### PR TITLE
Add Inventory/Location endpoints and tests

### PR DESCRIPTION
**Pull request by theducvu**
The Inventory/Location endpoint can be found here on the API docs: https://developer.myob.com/api/accountright/v2/inventory/location/

### CODE REVIEW

**Comment by jarekwg** [comment]
Thank you!
Still got one failing test -- I'm not sure why the travis checks aren't appearing in github..
https://travis-ci.org/github/uptick/pymyob/jobs/702998835

**Comment by theducvu** [comment]
That is strange, I was wondering why I'm not seeing the test results. Anyway, I've fixed the issue, I hope.

**Comment by jarekwg** [comment]
Mm, something must've changed.. ;/

Anyway, thanks for quick update!

**Comment by jarekwg** [comment]
Out in [1.2.6](https://github.com/uptick/pymyob/releases/tag/1.2.6).

**Pull request merged**
